/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --shadows --instance oval-track.glb 
Files: oval-track.glb [4.58MB] > /Users/chaseashton/Developer/Mario-Kart-Trainer/public/models/oval-track-transformed.glb [418.2KB] (91%)
*/

import React, {useRef, useEffect } from 'react'
import { useGameStore } from '../store'
import { useGLTF } from '@react-three/drei'

export function Track(props) {
    const { nodes, materials, scene } = useGLTF('./models/oval-track-transformed.glb')
    const trackRef = useRef(null)
    
    const setTrackScene = useGameStore((state) => state.setTrackScene);
    useEffect(() => {
      if(setTrackScene && trackRef.current){
        setTrackScene(trackRef.current)
      }
    }, [setTrackScene])

  return (
    <group {...props} position={[0, -3.65, 334]}dispose={null}>
      <mesh name="mountains" layers={1} castShadow receiveShadow geometry={nodes.Mountains.geometry} material={materials.Mountains} />
      <mesh ref={trackRef} name="road" layers={1} castShadow receiveShadow geometry={nodes.oval_road.geometry} material={materials.Road} />
    </group>
  )
}

useGLTF.preload('./models/oval-track-transformed.glb')
