/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --transform wheel.glb 
Files: wheel.glb [328.66KB] > C:\Users\mouli\mk3\public\models\wheel-transformed.glb [26.7KB] (92%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { damp } from "three/src/math/MathUtils.js";

export function Wheels({speed, inputTurn}) {
  const { nodes, materials } = useGLTF("./models/wheel-transformed.glb");
    const wheel3 = useRef(null);
    const wheel2 = useRef(null);
    const wheel1 = useRef(null);
    const wheel0 = useRef(null);
    const frontWheels = useRef(null);
    const yRotation = useRef(0);
    
    const wheel0Base = useRef(null)
    const wheel1Base = useRef(null)
    const wheel2Base = useRef(null)
    const wheel3Base = useRef(null)

    const rotateWheels = (delta) => {
      const rotationSpeed = -speed.current * 0.01;
          wheel0.current.rotation.x += rotationSpeed;
          wheel1.current.rotation.x += rotationSpeed;
          wheel2.current.rotation.x += rotationSpeed;
          wheel3.current.rotation.x += rotationSpeed;
      
          yRotation.current = damp(
            yRotation.current,
            inputTurn.current * 2,
            4, delta
          );
      
          frontWheels.current.rotation.y = yRotation.current;
    }

    useFrame(({}, delta) => {
      rotateWheels(delta);
    })
  return (
    <group  dispose={null}>
      <mesh ref={wheel0}
        position={[-0.35, -0.079, 0.35]}
        geometry={nodes.wheel_3.geometry}
        material={materials.m_Tire}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.522}
      />
      <mesh ref={wheel1}
        position={[0.35, -0.079, 0.35]}
        geometry={nodes.wheel_3.geometry}
        material={materials.m_Tire}
        rotation={[Math.PI, Math.PI, Math.PI]}
        scale={0.522}
      />
      <group ref={frontWheels}>
        <mesh ref={wheel2}
          position={[-0.35, -0.095, -0.37]}
          geometry={nodes.wheel_3.geometry}
          material={materials.m_Tire}
          rotation={[Math.PI, 0, Math.PI]}
          scale={0.45}
        />
        <mesh ref={wheel3}
          position={[0.35, -0.095, -0.37]}
          geometry={nodes.wheel_3.geometry}
          material={materials.m_Tire}
          rotation={[Math.PI, Math.PI, Math.PI]}
          scale={0.45}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/wheel-transformed.glb");
